name: 'vrelease-action'
description: 'vrelease action for github'
author: 'Caian Ertl <hi@caian.org>'

inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'

runs:
  using: 'node16'
  main: 'dist/index.js'
